[advisories]
vulnerability = "deny"
unmaintained = "warn"
unsound = "deny"
yanked = "warn"

[licenses]
allow = [
    "MIT",
]
deny = [
    "GPL-2.0",
]

[bans]
multiple-versions = "warn"
wildcards = "warn"